name: Build

on:
  push:
  pull_request:



jobs:
  build:
    #运行系统
    runs-on: macos-10.15
    
    steps:
    - uses: actions/checkout@v1

    # c++ 测试
    - name: cmake test
      run: |
        mkdir build && cd build
        cmake ..
        make


